version: 2

project_name: bridgectl

builds:
  - id: bridge-ca
    binary: bridge-ca
    main: ./cmd/bridge-ca
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: bridgectl
    binary: bridgectl
    main: ./cmd/bridgectl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

dockers:
  - id: bridge-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/orchael/bridgectl:{{ .Tag }}-amd64"
      - "ghcr.io/orchael/bridgectl:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - docker-entrypoint.sh
      - config/bridge.yaml
    build_flag_templates:
      - "--build-arg=BUILD_FROM=prebuilt"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - id: bridge-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/orchael/bridgectl:{{ .Tag }}-arm64"
      - "ghcr.io/orchael/bridgectl:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - docker-entrypoint.sh
      - config/bridge.yaml
    build_flag_templates:
      - "--build-arg=BUILD_FROM=prebuilt"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/orchael/bridgectl:{{ .Tag }}"
    image_templates:
      - "ghcr.io/orchael/bridgectl:{{ .Tag }}-amd64"
      - "ghcr.io/orchael/bridgectl:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/orchael/bridgectl:latest"
    image_templates:
      - "ghcr.io/orchael/bridgectl:latest-amd64"
      - "ghcr.io/orchael/bridgectl:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"
