allowBuilds:
  '@anthropic-ai/claude-code': true
  '@github/keytar': true
  node-pty: true
  opencode-ai: true
minimumReleaseAgeExclude:
  - '@openai/codex@0.148.0-darwin-x64'
onlyBuiltDependencies:
  - node-pty
  - '@anthropic-ai/claude-code'
  - '@github/keytar'
  - opencode-ai
