FROM golang:1.25-bookworm

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /usr/local/bin/bridgectl ./cmd/bridgectl

COPY e2e/system-daemon/test.sh /test.sh
RUN chmod +x /test.sh

CMD ["/test.sh"]
